/*
 * FINBOURNE Drive API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.328-MB
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.drive.api;

import com.finbourne.drive.ApiException;
import com.finbourne.drive.model.LusidProblemDetails;
import com.finbourne.drive.model.ResourceListOfAccessControlledResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApplicationMetadataApi
 */
@Ignore
public class ApplicationMetadataApiTest {

    private final ApplicationMetadataApi api = new ApplicationMetadataApi();

    
    /**
     * [EARLY ACCESS] ListAccessControlledResources: Get resources available for access control
     *
     * Get the comprehensive set of resources that are available for access control
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccessControlledResourcesTest() throws ApiException {
        ResourceListOfAccessControlledResource response = api.listAccessControlledResources();

        // TODO: test validations
    }
    
}
