/*
 * FINBOURNE Drive API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.328-MB
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.drive.api;

import com.finbourne.drive.ApiException;
import java.io.File;
import com.finbourne.drive.model.LusidProblemDetails;
import com.finbourne.drive.model.LusidValidationProblemDetails;
import com.finbourne.drive.model.StorageObject;
import com.finbourne.drive.model.UpdateFile;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FilesApi
 */
@Ignore
public class FilesApiTest {

    private final FilesApi api = new FilesApi();

    
    /**
     * [BETA] CreateFile: Uploads a file to Lusid Drive. If using an SDK, consider using the UploadAsStreamAsync function for larger files instead.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFileTest() throws ApiException {
        String xLusidDriveFilename = null;
        String xLusidDrivePath = null;
        Integer contentLength = null;
        byte[] body = null;
        StorageObject response = api.createFile(xLusidDriveFilename, xLusidDrivePath, contentLength, body);

        // TODO: test validations
    }
    
    /**
     * [BETA] DeleteFile: Deletes a file from Drive.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFileTest() throws ApiException {
        String id = null;
        api.deleteFile(id);

        // TODO: test validations
    }
    
    /**
     * [BETA] DownloadFile: Download the file from Drive.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void downloadFileTest() throws ApiException {
        String id = null;
        File response = api.downloadFile(id);

        // TODO: test validations
    }
    
    /**
     * [BETA] GetFile: Get a file stored in Drive.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFileTest() throws ApiException {
        String id = null;
        StorageObject response = api.getFile(id);

        // TODO: test validations
    }
    
    /**
     * [BETA] UpdateFileContents: Updates contents of a file in Drive.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFileContentsTest() throws ApiException {
        String id = null;
        Integer contentLength = null;
        byte[] body = null;
        StorageObject response = api.updateFileContents(id, contentLength, body);

        // TODO: test validations
    }
    
    /**
     * [BETA] UpdateFileMetadata: Updates metadata for a file in Drive.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFileMetadataTest() throws ApiException {
        String id = null;
        UpdateFile updateFile = null;
        StorageObject response = api.updateFileMetadata(id, updateFile);

        // TODO: test validations
    }
    
}
