/*
 * FINBOURNE Drive API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.328
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.finbourne.drive.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DTO representing the search query
 */
@ApiModel(description = "DTO representing the search query")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SearchBody {
  public static final String SERIALIZED_NAME_WITH_PATH = "withPath";
  @SerializedName(SERIALIZED_NAME_WITH_PATH)
  private String withPath;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public SearchBody withPath(String withPath) {
    this.withPath = withPath; 
    return this;
  }

   /**
   * Optional path field to limit the search to result with a matching (case insensitive) path
   * @return withPath
  **/
  @ApiModelProperty(value = "Optional path field to limit the search to result with a matching (case insensitive) path")
  public String getWithPath() {
    return withPath;
  }

  public void setWithPath(String withPath) {
    this.withPath = withPath;
  }


  public SearchBody name(String name) {
    this.name = name; 
    return this;
  }

   /**
   * Name of the file or folder to be searched
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the file or folder to be searched")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public int hashCode() {
    return super.hashCode();  
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchBody {\n");
    sb.append("    withPath: ").append(toIndentedString(withPath)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
